prompts: [prompts.txt]
providers: [openai:gpt-3.5-turbo-0613]
tests:
  - description: First test case - automatic review
    vars:
      var3: What is fs in node
    assert:
      - type: contains
        value: fs