# This configuration runs each prompt through a series of example inputs and checks if they meet requirements.

prompts: [prompts.txt]
providers: [openai:gpt-3.5-turbo-0613]
options: {
  max-tokens: 2
}
defaultTest:
  assert:
tests:
  - description: 'Test translation to German'
    vars:
      language: French
      input: How's it going?
    assert:
      - type: contains
        value: geh
      - type: similar
        value: was geht
        threshold: 0.9 # cosine similarity
outputPath: outputj.json